import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { customerMapUrl, formatDate } from "@/lib/filterUi";
import { BellRing, Check, MapPinned, Phone, X } from "lucide-react";
import { toast } from "sonner";
import { useLocation } from "wouter";

export default function Reminders() {
  const { data: reminders, isLoading, isError } = trpc.filters.reminders.due.useQuery();
  const utils = trpc.useUtils();
  const [, setLocation] = useLocation();
  const updateStatus = trpc.filters.reminders.updateStatus.useMutation({ onSuccess: () => { utils.filters.reminders.due.invalidate(); utils.filters.dashboard.invalidate(); toast.success("تم تحديث حالة التذكير"); }, onError: error => toast.error(error.message || "تعذر تحديث حالة التذكير. يرجى المحاولة مرة أخرى.") });
  if (isError) return <div className="soft-card p-8 text-center"><p className="font-bold text-teal-950">تعذر تحميل التذكيرات المستحقة.</p><p className="mt-2 text-sm text-muted-foreground">تحقق من الاتصال ثم أعد المحاولة.</p><Button onClick={() => window.location.reload()} variant="outline" className="mt-4 rounded-xl">إعادة المحاولة</Button></div>;
  return <div className="mx-auto max-w-6xl space-y-6"><div><h1 className="page-heading">التذكيرات المستحقة</h1><p className="page-subheading">العملاء الذين مرّ على تركيبهم أو صيانة فلترهم 120 يومًا ويحتاجون متابعة.</p></div><section className="soft-card overflow-hidden"><div className="flex items-center justify-between border-b border-teal-950/6 p-5"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-amber-100 text-amber-700"><BellRing className="h-5 w-5" /></div><div><h2 className="font-extrabold">قائمة المتابعة</h2><p className="mt-1 text-xs text-muted-foreground">{isLoading ? "جارٍ التحميل…" : `${reminders?.length || 0} عميل مستحق`}</p></div></div></div><div className="divide-y divide-teal-950/6">{reminders?.length ? reminders.map(reminder => { const mapUrl = reminder.customer ? customerMapUrl(reminder.customer) : null; return <div key={reminder.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><button onClick={() => setLocation(`/customers/${reminder.customerId}`)} className="font-extrabold text-teal-900 hover:text-teal-600">{reminder.customer?.name || "عميل"}</button><div className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-xs text-muted-foreground"><span dir="ltr">{reminder.customer?.phone}</span><span>استحق في {formatDate(reminder.reminderDate)}</span></div></div><div className="flex flex-wrap items-center gap-2"><a href={`tel:${reminder.customer?.phone || ""}`} className="inline-flex h-9 items-center rounded-lg bg-teal-50 px-3 text-sm font-bold text-teal-800 hover:bg-teal-100"><Phone className="ml-1.5 h-4 w-4" />اتصال</a>{mapUrl ? <a href={mapUrl} target="_blank" rel="noreferrer" className="inline-flex h-9 items-center rounded-lg bg-sky-50 px-3 text-sm font-bold text-sky-800 hover:bg-sky-100"><MapPinned className="ml-1.5 h-4 w-4" />الموقع</a> : null}<Button size="sm" disabled={updateStatus.isPending} onClick={() => updateStatus.mutate({ id: reminder.id, status: "completed" })} className="h-9 rounded-lg bg-teal-700 hover:bg-teal-800"><Check className="ml-1 h-4 w-4" />تمت</Button><Button size="sm" variant="outline" disabled={updateStatus.isPending} onClick={() => updateStatus.mutate({ id: reminder.id, status: "dismissed" })} className="h-9 rounded-lg border-amber-200 text-amber-800 hover:bg-amber-50"><X className="ml-1 h-4 w-4" />تجاوز</Button></div></div>; }) : <div className="p-14 text-center"><BellRing className="mx-auto h-8 w-8 text-teal-200" /><p className="mt-3 text-sm text-muted-foreground">لا توجد تذكيرات مستحقة حاليًا.</p></div>}</div></section></div>;
}
